name = "nikunj-site"
main = "src/index.ts"
compatibility_date = "2026-08-10"

[vars]
ALLOW_REGISTRATION = "true"
SUPABASE_URL = "your-supabase-url"
SUPABASE_ANON_KEY = "your-supabase-anon-key"

[assets]
directory = "./public"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
