name = "nikunj-site"
main = "src/index.ts"
compatibility_date = "2026-08-10"

[vars]
ALLOW_REGISTRATION = "true"
SUPABASE_URL = "https://alzanbffcpiiqyezijaa.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsemFuYmZmY3BpaXF5ZXppamFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3NTkxOTcsImV4cCI6MjEwMjMzNTE5N30.7IytLJfodgDVIy5ExnctFqp4D1kjPVa-rTiK9dC8f8U"

[assets]
directory = "./public"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
